void ACodecAudioCapabilities_getBitrateRange() {}
void ACodecAudioCapabilities_getInputChannelCountRanges() {}
void ACodecAudioCapabilities_getMaxInputChannelCount() {}
void ACodecAudioCapabilities_getMinInputChannelCount() {}
void ACodecAudioCapabilities_getSupportedSampleRateRanges() {}
void ACodecAudioCapabilities_getSupportedSampleRates() {}
void ACodecAudioCapabilities_isSampleRateSupported() {}
void ACodecEncoderCapabilities_getComplexityRange() {}
void ACodecEncoderCapabilities_getQualityRange() {}
void ACodecEncoderCapabilities_isBitrateModeSupported() {}
void ACodecPerformancePoint_covers() {}
void ACodecPerformancePoint_coversFormat() {}
void ACodecPerformancePoint_create() {}
void ACodecPerformancePoint_destroy() {}
void ACodecPerformancePoint_equals() {}
void ACodecVideoCapabilities_areSizeAndRateSupported() {}
void ACodecVideoCapabilities_getAchievableFrameRatesFor() {}
void ACodecVideoCapabilities_getBitrateRange() {}
void ACodecVideoCapabilities_getHeightAlignment() {}
void ACodecVideoCapabilities_getNextSupportedPerformancePoint() {}
void ACodecVideoCapabilities_getSupportedFrameRates() {}
void ACodecVideoCapabilities_getSupportedFrameRatesFor() {}
void ACodecVideoCapabilities_getSupportedHeights() {}
void ACodecVideoCapabilities_getSupportedHeightsFor() {}
void ACodecVideoCapabilities_getSupportedWidths() {}
void ACodecVideoCapabilities_getSupportedWidthsFor() {}
void ACodecVideoCapabilities_getWidthAlignment() {}
void ACodecVideoCapabilities_isSizeSupported() {}
void AImage_delete() {}
void AImage_deleteAsync() {}
void AImage_getCropRect() {}
void AImage_getDataSpace() {}
void AImage_getFormat() {}
void AImage_getHardwareBuffer() {}
void AImage_getHeight() {}
void AImage_getNumberOfPlanes() {}
void AImage_getPlaneData() {}
void AImage_getPlanePixelStride() {}
void AImage_getPlaneRowStride() {}
void AImage_getTimestamp() {}
void AImage_getWidth() {}
void AImageReader_acquireLatestImage() {}
void AImageReader_acquireLatestImageAsync() {}
void AImageReader_acquireNextImage() {}
void AImageReader_acquireNextImageAsync() {}
void AImageReader_delete() {}
void AImageReader_getFormat() {}
void AImageReader_getHeight() {}
void AImageReader_getMaxImages() {}
void AImageReader_getWidth() {}
void AImageReader_getWindow() {}
void AImageReader_getWindowNativeHandle() {}
void AImageReader_new() {}
void AImageReader_newWithDataSpace() {}
void AImageReader_newWithUsage() {}
void AImageReader_setBufferRemovedListener() {}
void AImageReader_setImageListener() {}
void AImageReader_setUsage() {}
void AMediaCodecActionCode_isRecoverable() {}
void AMediaCodecActionCode_isTransient() {}
void AMediaCodec_configure() {}
void AMediaCodec_createCodecByName() {}
void AMediaCodec_createCodecByNameForClient() {}
void AMediaCodec_createDecoderByType() {}
void AMediaCodec_createDecoderByTypeForClient() {}
void AMediaCodec_createEncoderByType() {}
void AMediaCodec_createEncoderByTypeForClient() {}
void AMediaCodec_createInputSurface() {}
void AMediaCodec_createPersistentInputSurface() {}
void AMediaCodecCryptoInfo_delete() {}
void AMediaCodecCryptoInfo_getClearBytes() {}
void AMediaCodecCryptoInfo_getEncryptedBytes() {}
void AMediaCodecCryptoInfo_getIV() {}
void AMediaCodecCryptoInfo_getKey() {}
void AMediaCodecCryptoInfo_getMode() {}
void AMediaCodecCryptoInfo_getNumSubSamples() {}
void AMediaCodecCryptoInfo_new() {}
void AMediaCodecCryptoInfo_setPattern() {}
void AMediaCodec_delete() {}
void AMediaCodec_dequeueInputBuffer() {}
void AMediaCodec_dequeueOutputBuffer() {}
void AMediaCodec_flush() {}
void AMediaCodec_getBufferFormat() {}
void AMediaCodec_getInputBuffer() {}
void AMediaCodec_getInputFormat() {}
void AMediaCodec_getName() {}
void AMediaCodec_getOutputBuffer() {}
void AMediaCodec_getOutputFormat() {}
void AMediaCodecInfo_FEATURE_AdaptivePlayback() {}
void AMediaCodecInfo_FEATURE_DetachedSurface() {}
void AMediaCodecInfo_FEATURE_DynamicColorAspects() {}
void AMediaCodecInfo_FEATURE_DynamicTimestamp() {}
void AMediaCodecInfo_FEATURE_EncodingStatistics() {}
void AMediaCodecInfo_FEATURE_FrameParsing() {}
void AMediaCodecInfo_FEATURE_HdrEditing() {}
void AMediaCodecInfo_FEATURE_HlgEditing() {}
void AMediaCodecInfo_FEATURE_IntraRefresh() {}
void AMediaCodecInfo_FEATURE_LowLatency() {}
void AMediaCodecInfo_FEATURE_MultipleFrames() {}
void AMediaCodecInfo_FEATURE_PartialFrame() {}
void AMediaCodecInfo_FEATURE_QpBounds() {}
void AMediaCodecInfo_FEATURE_Roi() {}
void AMediaCodecInfo_FEATURE_SecurePlayback() {}
void AMediaCodecInfo_FEATURE_TunneledPlayback() {}
void AMediaCodecInfo_getAudioCapabilities() {}
void AMediaCodecInfo_getCanonicalName() {}
void AMediaCodecInfo_getEncoderCapabilities() {}
void AMediaCodecInfo_getKind() {}
void AMediaCodecInfo_getMaxSupportedInstances() {}
void AMediaCodecInfo_getMediaCodecInfoType() {}
void AMediaCodecInfo_getMediaType() {}
void AMediaCodecInfo_getVideoCapabilities() {}
void AMediaCodecInfo_isFeatureRequired() {}
void AMediaCodecInfo_isFeatureSupported() {}
void AMediaCodecInfo_isFormatSupported() {}
void AMediaCodecInfo_isVendor() {}
void AMEDIACODEC_KEY_HDR10_PLUS_INFO() {}
void AMEDIACODEC_KEY_LOW_LATENCY() {}
void AMEDIACODEC_KEY_OFFSET_TIME() {}
void AMEDIACODEC_KEY_REQUEST_SYNC_FRAME() {}
void AMEDIACODEC_KEY_SUSPEND() {}
void AMEDIACODEC_KEY_SUSPEND_TIME() {}
void AMEDIACODEC_KEY_VIDEO_BITRATE() {}
void AMediaCodec_queueInputBuffer() {}
void AMediaCodec_queueSecureInputBuffer() {}
void AMediaCodec_releaseCrypto() {}
void AMediaCodec_releaseName() {}
void AMediaCodec_releaseOutputBuffer() {}
void AMediaCodec_releaseOutputBufferAtTime() {}
void AMediaCodec_setAsyncNotifyCallback() {}
void AMediaCodec_setInputSurface() {}
void AMediaCodec_setOnFrameRenderedCallback() {}
void AMediaCodec_setOutputSurface() {}
void AMediaCodec_setParameters() {}
void AMediaCodec_signalEndOfInputStream() {}
void AMediaCodec_start() {}
void AMediaCodec_stop() {}
void AMediaCodecStore_findNextDecoderForFormat() {}
void AMediaCodecStore_findNextEncoderForFormat() {}
void AMediaCodecStore_getCodecInfo() {}
void AMediaCodecStore_getSupportedMediaTypes() {}
void AMediaCrypto_delete() {}
void AMediaCrypto_isCryptoSchemeSupported() {}
void AMediaCrypto_new() {}
void AMediaCrypto_requiresSecureDecoderComponent() {}
void AMediaDataSource_close() {}
void AMediaDataSource_delete() {}
void AMediaDataSource_new() {}
void AMediaDataSource_newUri() {}
void AMediaDataSource_setClose() {}
void AMediaDataSource_setGetAvailableSize() {}
void AMediaDataSource_setGetSize() {}
void AMediaDataSource_setReadAt() {}
void AMediaDataSource_setUserdata() {}
void AMediaDrm_closeSession() {}
void AMediaDrm_createByUUID() {}
void AMediaDrm_decrypt() {}
void AMediaDrm_encrypt() {}
void AMediaDrm_getKeyRequest() {}
void AMediaDrm_getKeyRequestWithDefaultUrlAndType() {}
void AMediaDrm_getPropertyByteArray() {}
void AMediaDrm_getPropertyString() {}
void AMediaDrm_getProvisionRequest() {}
void AMediaDrm_getSecureStops() {}
void AMediaDrm_isCryptoSchemeSupported() {}
void AMediaDrm_openSession() {}
void AMediaDrm_provideKeyResponse() {}
void AMediaDrm_provideProvisionResponse() {}
void AMediaDrm_queryKeyStatus() {}
void AMediaDrm_release() {}
void AMediaDrm_releaseSecureStops() {}
void AMediaDrm_removeKeys() {}
void AMediaDrm_restoreKeys() {}
void AMediaDrm_setOnEventListener() {}
void AMediaDrm_setOnExpirationUpdateListener() {}
void AMediaDrm_setOnKeysChangeListener() {}
void AMediaDrm_setPropertyByteArray() {}
void AMediaDrm_setPropertyString() {}
void AMediaDrm_sign() {}
void AMediaDrm_verify() {}
void AMediaExtractor_advance() {}
void AMediaExtractor_delete() {}
void AMediaExtractor_getCachedDuration() {}
void AMediaExtractor_getFileFormat() {}
void AMediaExtractor_getPsshInfo() {}
void AMediaExtractor_getSampleCryptoInfo() {}
void AMediaExtractor_getSampleFlags() {}
void AMediaExtractor_getSampleFormat() {}
void AMediaExtractor_getSampleSize() {}
void AMediaExtractor_getSampleTime() {}
void AMediaExtractor_getSampleTrackIndex() {}
void AMediaExtractor_getTrackCount() {}
void AMediaExtractor_getTrackFormat() {}
void AMediaExtractor_new() {}
void AMediaExtractor_readSampleData() {}
void AMediaExtractor_seekTo() {}
void AMediaExtractor_selectTrack() {}
void AMediaExtractor_setDataSource() {}
void AMediaExtractor_setDataSourceCustom() {}
void AMediaExtractor_setDataSourceFd() {}
void AMediaExtractor_unselectTrack() {}
void AMediaFormat_clear() {}
void AMediaFormat_copy() {}
void AMediaFormat_delete() {}
void AMediaFormat_getBuffer() {}
void AMediaFormat_getDouble() {}
void AMediaFormat_getFloat() {}
void AMediaFormat_getInt32() {}
void AMediaFormat_getInt64() {}
void AMediaFormat_getRect() {}
void AMediaFormat_getSize() {}
void AMediaFormat_getString() {}
void AMEDIAFORMAT_KEY_AAC_DRC_ATTENUATION_FACTOR() {}
void AMEDIAFORMAT_KEY_AAC_DRC_BOOST_FACTOR() {}
void AMEDIAFORMAT_KEY_AAC_DRC_HEAVY_COMPRESSION() {}
void AMEDIAFORMAT_KEY_AAC_DRC_TARGET_REFERENCE_LEVEL() {}
void AMEDIAFORMAT_KEY_AAC_ENCODED_TARGET_LEVEL() {}
void AMEDIAFORMAT_KEY_AAC_MAX_OUTPUT_CHANNEL_COUNT() {}
void AMEDIAFORMAT_KEY_AAC_PROFILE() {}
void AMEDIAFORMAT_KEY_AAC_SBR_MODE() {}
void AMEDIAFORMAT_KEY_ALBUM() {}
void AMEDIAFORMAT_KEY_ALBUMART() {}
void AMEDIAFORMAT_KEY_ALBUMARTIST() {}
void AMEDIAFORMAT_KEY_ALLOW_FRAME_DROP() {}
void AMEDIAFORMAT_KEY_ARTIST() {}
void AMEDIAFORMAT_KEY_AUDIO_PRESENTATION_INFO() {}
void AMEDIAFORMAT_KEY_AUDIO_SESSION_ID() {}
void AMEDIAFORMAT_KEY_AUTHOR() {}
void AMEDIAFORMAT_KEY_BIT_RATE() {}
void AMEDIAFORMAT_KEY_BITRATE_MODE() {}
void AMEDIAFORMAT_KEY_BITS_PER_SAMPLE() {}
void AMEDIAFORMAT_KEY_CAPTURE_RATE() {}
void AMEDIAFORMAT_KEY_CDTRACKNUMBER() {}
void AMEDIAFORMAT_KEY_CHANNEL_COUNT() {}
void AMEDIAFORMAT_KEY_CHANNEL_MASK() {}
void AMEDIAFORMAT_KEY_COLOR_FORMAT() {}
void AMEDIAFORMAT_KEY_COLOR_RANGE() {}
void AMEDIAFORMAT_KEY_COLOR_STANDARD() {}
void AMEDIAFORMAT_KEY_COLOR_TRANSFER() {}
void AMEDIAFORMAT_KEY_COMPILATION() {}
void AMEDIAFORMAT_KEY_COMPLEXITY() {}
void AMEDIAFORMAT_KEY_COMPOSER() {}
void AMEDIAFORMAT_KEY_CREATE_INPUT_SURFACE_SUSPENDED() {}
void AMEDIAFORMAT_KEY_CRYPTO_DEFAULT_IV_SIZE() {}
void AMEDIAFORMAT_KEY_CRYPTO_ENCRYPTED_BYTE_BLOCK() {}
void AMEDIAFORMAT_KEY_CRYPTO_ENCRYPTED_SIZES() {}
void AMEDIAFORMAT_KEY_CRYPTO_IV() {}
void AMEDIAFORMAT_KEY_CRYPTO_KEY() {}
void AMEDIAFORMAT_KEY_CRYPTO_MODE() {}
void AMEDIAFORMAT_KEY_CRYPTO_PLAIN_SIZES() {}
void AMEDIAFORMAT_KEY_CRYPTO_SKIP_BYTE_BLOCK() {}
void AMEDIAFORMAT_KEY_CSD() {}
void AMEDIAFORMAT_KEY_CSD_0() {}
void AMEDIAFORMAT_KEY_CSD_1() {}
void AMEDIAFORMAT_KEY_CSD_2() {}
void AMEDIAFORMAT_KEY_CSD_AVC() {}
void AMEDIAFORMAT_KEY_CSD_HEVC() {}
void AMEDIAFORMAT_KEY_D263() {}
void AMEDIAFORMAT_KEY_DATE() {}
void AMEDIAFORMAT_KEY_DISCNUMBER() {}
void AMEDIAFORMAT_KEY_DISPLAY_CROP() {}
void AMEDIAFORMAT_KEY_DISPLAY_HEIGHT() {}
void AMEDIAFORMAT_KEY_DISPLAY_WIDTH() {}
void AMEDIAFORMAT_KEY_DURATION() {}
void AMEDIAFORMAT_KEY_ENCODER_DELAY() {}
void AMEDIAFORMAT_KEY_ENCODER_PADDING() {}
void AMEDIAFORMAT_KEY_ESDS() {}
void AMEDIAFORMAT_KEY_EXIF_OFFSET() {}
void AMEDIAFORMAT_KEY_EXIF_SIZE() {}
void AMEDIAFORMAT_KEY_FLAC_COMPRESSION_LEVEL() {}
void AMEDIAFORMAT_KEY_FRAME_COUNT() {}
void AMEDIAFORMAT_KEY_FRAME_RATE() {}
void AMEDIAFORMAT_KEY_GENRE() {}
void AMEDIAFORMAT_KEY_GRID_COLUMNS() {}
void AMEDIAFORMAT_KEY_GRID_ROWS() {}
void AMEDIAFORMAT_KEY_HAPTIC_CHANNEL_COUNT() {}
void AMEDIAFORMAT_KEY_HDR10_PLUS_INFO() {}
void AMEDIAFORMAT_KEY_HDR_STATIC_INFO() {}
void AMEDIAFORMAT_KEY_HEIGHT() {}
void AMEDIAFORMAT_KEY_ICC_PROFILE() {}
void AMEDIAFORMAT_KEY_I_FRAME_INTERVAL() {}
void AMEDIAFORMAT_KEY_INTRA_REFRESH_PERIOD() {}
void AMEDIAFORMAT_KEY_IS_ADTS() {}
void AMEDIAFORMAT_KEY_IS_AUTOSELECT() {}
void AMEDIAFORMAT_KEY_IS_DEFAULT() {}
void AMEDIAFORMAT_KEY_IS_FORCED_SUBTITLE() {}
void AMEDIAFORMAT_KEY_IS_SYNC_FRAME() {}
void AMEDIAFORMAT_KEY_LANGUAGE() {}
void AMEDIAFORMAT_KEY_LAST_SAMPLE_INDEX_IN_CHUNK() {}
void AMEDIAFORMAT_KEY_LATENCY() {}
void AMEDIAFORMAT_KEY_LEVEL() {}
void AMEDIAFORMAT_KEY_LOCATION() {}
void AMEDIAFORMAT_KEY_LOOP() {}
void AMEDIAFORMAT_KEY_LOW_LATENCY() {}
void AMEDIAFORMAT_KEY_LYRICIST() {}
void AMEDIAFORMAT_KEY_MANUFACTURER() {}
void AMEDIAFORMAT_KEY_MAX_B_FRAMES() {}
void AMEDIAFORMAT_KEY_MAX_BIT_RATE() {}
void AMEDIAFORMAT_KEY_MAX_FPS_TO_ENCODER() {}
void AMEDIAFORMAT_KEY_MAX_HEIGHT() {}
void AMEDIAFORMAT_KEY_MAX_INPUT_SIZE() {}
void AMEDIAFORMAT_KEY_MAX_PTS_GAP_TO_ENCODER() {}
void AMEDIAFORMAT_KEY_MAX_WIDTH() {}
void AMEDIAFORMAT_KEY_MIME() {}
void AMEDIAFORMAT_KEY_MPEG2_STREAM_HEADER() {}
void AMEDIAFORMAT_KEY_MPEGH_COMPATIBLE_SETS() {}
void AMEDIAFORMAT_KEY_MPEGH_PROFILE_LEVEL_INDICATION() {}
void AMEDIAFORMAT_KEY_MPEGH_REFERENCE_CHANNEL_LAYOUT() {}
void AMEDIAFORMAT_KEY_MPEG_USER_DATA() {}
void AMEDIAFORMAT_KEY_OPERATING_RATE() {}
void AMEDIAFORMAT_KEY_PCM_BIG_ENDIAN() {}
void AMEDIAFORMAT_KEY_PCM_ENCODING() {}
void AMEDIAFORMAT_KEY_PRIORITY() {}
void AMEDIAFORMAT_KEY_PROFILE() {}
void AMEDIAFORMAT_KEY_PSSH() {}
void AMEDIAFORMAT_KEY_PUSH_BLANK_BUFFERS_ON_STOP() {}
void AMEDIAFORMAT_KEY_REPEAT_PREVIOUS_FRAME_AFTER() {}
void AMEDIAFORMAT_KEY_ROTATION() {}
void AMEDIAFORMAT_KEY_SAMPLE_FILE_OFFSET() {}
void AMEDIAFORMAT_KEY_SAMPLE_RATE() {}
void AMEDIAFORMAT_KEY_SAMPLE_TIME_BEFORE_APPEND() {}
void AMEDIAFORMAT_KEY_SAR_HEIGHT() {}
void AMEDIAFORMAT_KEY_SAR_WIDTH() {}
void AMEDIAFORMAT_KEY_SEI() {}
void AMEDIAFORMAT_KEY_SLICE_HEIGHT() {}
void AMEDIAFORMAT_KEY_SLOW_MOTION_MARKERS() {}
void AMEDIAFORMAT_KEY_STRIDE() {}
void AMEDIAFORMAT_KEY_TARGET_TIME() {}
void AMEDIAFORMAT_KEY_TEMPORAL_LAYER_COUNT() {}
void AMEDIAFORMAT_KEY_TEMPORAL_LAYER_ID() {}
void AMEDIAFORMAT_KEY_TEMPORAL_LAYERING() {}
void AMEDIAFORMAT_KEY_TEXT_FORMAT_DATA() {}
void AMEDIAFORMAT_KEY_THUMBNAIL_CSD_AV1C() {}
void AMEDIAFORMAT_KEY_THUMBNAIL_CSD_HEVC() {}
void AMEDIAFORMAT_KEY_THUMBNAIL_HEIGHT() {}
void AMEDIAFORMAT_KEY_THUMBNAIL_TIME() {}
void AMEDIAFORMAT_KEY_THUMBNAIL_WIDTH() {}
void AMEDIAFORMAT_KEY_TILE_HEIGHT() {}
void AMEDIAFORMAT_KEY_TILE_WIDTH() {}
void AMEDIAFORMAT_KEY_TIME_US() {}
void AMEDIAFORMAT_KEY_TITLE() {}
void AMEDIAFORMAT_KEY_TRACK_ID() {}
void AMEDIAFORMAT_KEY_TRACK_INDEX() {}
void AMEDIAFORMAT_KEY_VALID_SAMPLES() {}
void AMEDIAFORMAT_KEY_WIDTH() {}
void AMEDIAFORMAT_KEY_XMP_OFFSET() {}
void AMEDIAFORMAT_KEY_XMP_SIZE() {}
void AMEDIAFORMAT_KEY_YEAR() {}
void AMediaFormat_new() {}
void AMediaFormat_setBuffer() {}
void AMediaFormat_setDouble() {}
void AMediaFormat_setFloat() {}
void AMediaFormat_setInt32() {}
void AMediaFormat_setInt64() {}
void AMediaFormat_setRect() {}
void AMediaFormat_setSize() {}
void AMediaFormat_setString() {}
void AMediaFormat_toString() {}
void AMediaMuxer_addTrack() {}
void AMediaMuxer_append() {}
void AMediaMuxer_delete() {}
void AMediaMuxer_getTrackCount() {}
void AMediaMuxer_getTrackFormat() {}
void AMediaMuxer_new() {}
void AMediaMuxer_setLocation() {}
void AMediaMuxer_setOrientationHint() {}
void AMediaMuxer_start() {}
void AMediaMuxer_stop() {}
void AMediaMuxer_writeSampleData() {}
