name: Android Build

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  arm64_v8a:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            ant \
            autoconf \
            automake \
            ccache \
            cmake \
            g++ \
            gcc \
            git \
            lbzip2 \
            libffi-dev \
            libltdl-dev \
            libtool \
            libssl-dev \
            make \
            openjdk-17-jdk \
            patch \
            pkg-config \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv \
            sudo \
            unzip \
            wget \
            zip \
            zlib1g-dev \
            libncurses-dev
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: 13114758
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        link-to-sdk: true
        local-cache: true
    - name: Install target platform
      run: |
        sdkmanager "platforms;android-29"
        sdkmanager "build-tools;34.0.0"
    - name: Select NDK SDK for buildozer
      run: |
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        sed -i "s|^android.sdk_path =.*$|android.sdk_path = $ANDROID_SDK_ROOT|" buildozer.spec
        sed -i "s|^android.ndk_path =.*$|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec
    - name: Build Application
      run: |
        pip install wheel setuptools Cython buildozer
        buildozer android debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        path: .buildozer/android/platform/build-arm64-v8a/dists/pkit/build/outputs/apk/debug/pkit-debug.apk