name: Android Build

on:
  push:
  pull_request:

jobs:
  arm64_v8a:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            ant \
            liblzma-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            autoconf \
            automake \
            ccache \
            build-essential \
            lbzip2 \
            libffi-dev \
            libltdl-dev \
            libtool \
            libssl-dev \
            libreadline-dev \
            uuid-dev \
            zip \
            unzip \
            openjdk-17-jdk \
            cmake \
            libogg-dev \
            patch \
            pkg-config \
            zlib1g-dev \
            libncurses-dev
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Build Application
      run: |
        pip3 install --upgrade pip
        pip3 install --user virtualenv
        export PATH="$PATH:$HOME/.local/bin"
        python3 -m virtualenv venv
        source venv/bin/activate
        pip install wheel setuptools Cython==0.29.33 buildozer
        buildozer android debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: .buildozer/android/platform/build-arm64-v8a/dists/pkit/build/outputs/apk/debug/pkit-debug.apk